// <auto-generated />
using LNFreezerApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LNFreezerAPI.Migrations
{
    [DbContext(typeof(LNFreezerApiContext))]
    [Migration("20231215225843_UpdateSpecimenCohortDataType")]
    partial class UpdateSpecimenCohortDataType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LNFreezerApi.Models.Box", b =>
                {
                    b.Property<int>("BoxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BoxAlpha")
                        .HasColumnType("longtext");

                    b.Property<int>("RackId")
                        .HasColumnType("int");

                    b.HasKey("BoxId");

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("LNFreezerApi.Models.Freezer", b =>
                {
                    b.Property<int>("FreezerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FreezerNum")
                        .HasColumnType("int");

                    b.HasKey("FreezerId");

                    b.ToTable("Freezers");
                });

            modelBuilder.Entity("LNFreezerApi.Models.Rack", b =>
                {
                    b.Property<int>("RackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FreezerId")
                        .HasColumnType("int");

                    b.Property<int>("RackNum")
                        .HasColumnType("int");

                    b.HasKey("RackId");

                    b.ToTable("Racks");
                });

            modelBuilder.Entity("LNFreezerApi.Models.Specimen", b =>
                {
                    b.Property<int>("SpecimenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BoxId")
                        .HasColumnType("int");

                    b.Property<string>("Cohort")
                        .HasColumnType("longtext");

                    b.Property<int>("Date")
                        .HasColumnType("int");

                    b.Property<int>("NHPNum")
                        .HasColumnType("int");

                    b.Property<string>("Quantity")
                        .HasColumnType("longtext");

                    b.Property<int>("SpecimenNum")
                        .HasColumnType("int");

                    b.Property<string>("Tissue")
                        .HasColumnType("longtext");

                    b.HasKey("SpecimenId");

                    b.ToTable("Specimens");
                });
#pragma warning restore 612, 618
        }
    }
}
