// <auto-generated />
using LNFreezerApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LNFreezerAPI.Migrations
{
    [DbContext(typeof(LNFreezerApiContext))]
    partial class LNFreezerApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LNFreezerApi.Models.Box", b =>
                {
                    b.Property<int>("BoxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BoxAlpha")
                        .HasColumnType("longtext");

                    b.Property<int>("RackId")
                        .HasColumnType("int");

                    b.HasKey("BoxId");

                    b.ToTable("Boxes");

                    b.HasData(
                        new
                        {
                            BoxId = 1,
                            BoxAlpha = "A",
                            RackId = 1
                        });
                });

            modelBuilder.Entity("LNFreezerApi.Models.Freezer", b =>
                {
                    b.Property<int>("FreezerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FreezerNum")
                        .HasColumnType("int");

                    b.HasKey("FreezerId");

                    b.ToTable("Freezers");

                    b.HasData(
                        new
                        {
                            FreezerId = 1,
                            FreezerNum = 1
                        },
                        new
                        {
                            FreezerId = 2,
                            FreezerNum = 2
                        },
                        new
                        {
                            FreezerId = 3,
                            FreezerNum = 3
                        });
                });

            modelBuilder.Entity("LNFreezerApi.Models.Rack", b =>
                {
                    b.Property<int>("RackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FreezerId")
                        .HasColumnType("int");

                    b.Property<int>("RackNum")
                        .HasColumnType("int");

                    b.HasKey("RackId");

                    b.ToTable("Racks");

                    b.HasData(
                        new
                        {
                            RackId = 1,
                            FreezerId = 1,
                            RackNum = 1
                        },
                        new
                        {
                            RackId = 6,
                            FreezerId = 1,
                            RackNum = 6
                        },
                        new
                        {
                            RackId = 50,
                            FreezerId = 5,
                            RackNum = 30
                        },
                        new
                        {
                            RackId = 10,
                            FreezerId = 7,
                            RackNum = 30
                        });
                });

            modelBuilder.Entity("LNFreezerApi.Models.Specimen", b =>
                {
                    b.Property<int>("SpecimenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BoxId")
                        .HasColumnType("int");

                    b.Property<int>("Cohort")
                        .HasColumnType("int");

                    b.Property<int>("Date")
                        .HasColumnType("int");

                    b.Property<int>("NHPNum")
                        .HasColumnType("int");

                    b.Property<string>("Quantity")
                        .HasColumnType("longtext");

                    b.Property<int>("SpecimenNum")
                        .HasColumnType("int");

                    b.Property<string>("Tissue")
                        .HasColumnType("longtext");

                    b.HasKey("SpecimenId");

                    b.ToTable("Specimens");
                });
#pragma warning restore 612, 618
        }
    }
}
